version: "3"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
  api:
    image: graphql
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
      - mongo-express
